spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: s
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

  application:
    name: account-service
  active:
    profiles: dev

  #jpa configurations
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

server:
  port: 8081
