spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: card-service

  #jpa configurations
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082
